export { BAND_PROFILES, bandSamples, type BandProfile } from './bands.ts'
export {
  cellCentre,
  DEFAULT_CELL_M,
  evaluateCoverage,
  gridForFloor,
  predictDbm,
  RECEIVER_HEIGHT_M,
  type Coverage,
  type Grid,
} from './coverage.ts'
export {
  floorAreaMask,
  segmentsTouch,
  summariseCoverage,
  type CoverageSummary,
} from './floorArea.ts'
export { crossings, wallLoss, type Crossing } from './crossings.ts'
export {
  CONSTRUCTIONS,
  constructionLossDb,
  FLOOR_ANGLE_CAP_DEG,
  FLOOR_ANGLE_STEP_DEG,
  FLOOR_CONSTRUCTIONS,
  FLOOR_LOSS_DB,
  floorConstructionLossDb,
  floorLossAtDb,
  floorLossTable,
  LOW_E_SHEET_RESISTANCE_OHMS,
  MATERIAL_LOSS_DB,
  type Construction,
  type FloorConstruction,
  type FloorLossTable,
} from './materials.ts'
export {
  AUTO_WIDTH_MHZ,
  autoChannelCount,
  noiseFloorDbm,
  overlapShare,
  radioTuning,
  RECEIVER_NOISE_FIGURE_DB,
  requiredSinrDb,
  SENSITIVITY_20MHZ_DBM,
  sinrDb,
  sourceTunings,
  THERMAL_NOISE_DBM_PER_HZ,
  type Rate,
  type Tuning,
} from './interference.ts'
export { freeSpacePathLoss, SPEED_OF_LIGHT } from './pathLoss.ts'
export {
  betterScore,
  CANDIDATE_SPACING_M,
  candidatePositions,
  createScorer,
  SEARCH_CELL_M,
  WALL_CLEARANCE_M,
  type AccessPointTemplate,
  type PlacementProblem,
  type PlacementScore,
  type ScoredFloor,
  type Scorer,
  type Spot,
} from './placement.ts'
export {
  FITTED_MATERIALS,
  P2040_MATERIALS,
  slabLossDb,
  slabTransmission,
  type FittedMaterial,
  type Layer,
  type P2040Material,
  type Polarisation,
} from './slab.ts'
export {
  ANNEAL_SEED,
  ANNEAL_START_STEP_M,
  ANNEAL_STEPS_PER_AP,
  JUMP_CHANCE,
  MAX_ADDED,
  mulberry32,
  searchHowMany,
  searchMultiPlacement,
  type HowManyProblem,
  type HowManyResult,
  type MultiPlacementProblem,
  type MultiSearchResult,
} from './multiSearch.ts'
export {
  availableChannels,
  CHANNEL_WIDTHS,
  channelCentreMHz,
  channelSpanMHz,
  channelWidths,
  radioChannelIssue,
  REGION_RULES,
  REGIONS_VERSION,
  regionBand,
  type Channel,
  type ChannelIssue,
  type ChannelWidth,
  type RegionBand,
  type RegionRules,
} from './regions.ts'
export {
  REFINE_COUNT,
  REFINE_STEPS_M,
  SEARCH_BUDGET_MS,
  floorShares,
  searchSinglePlacement,
  type FloorShare,
  type SearchOptions,
  type SearchResult,
  type SinglePlacementProblem,
} from './search.ts'
export {
  handlePlacementRequest,
  handleRequest,
  transferables,
  type EngineRequest,
  type EngineResponse,
  type PlacementMessage,
  type PlacementRequest,
} from './worker.ts'
export {
  DEFAULT_OVERLAP_MARGIN_DB,
  DEFAULT_ROAM_THRESHOLD_DBM,
  overlapCounts,
  roamingEdges,
  roamingOwners,
  viewSettings,
  viewShares,
  type ViewSettings,
} from './views.ts'
